// Code generated by hertz generator.

package student

import (
	"context"
	"encoding/json"
	"github.com/cloudwego/kitex/pkg/klog"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"strconv"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	student "main/hz/biz/model/student"
)

var db *gorm.DB

var cache map[string]student.Student

var lock sync.RWMutex

func init() {
	var err error
	db, err = gorm.Open(sqlite.Open("foo.db"), &gorm.Config{})
	if err != nil {
		panic(err)
	}
	// drop table
	db.Migrator().DropTable(student.Student{})
	// create table
	err = db.Migrator().CreateTable(student.Student{})
	if err != nil {
		panic(err)
	}

	cache = make(map[string]student.Student)

}

// AddStudent .
// @router /add-student-info [POST]
func AddStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.SaveStudentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	data := student.Student{
		StudentNo:   req.StudentNo,
		StudentName: req.StudentName,
	}
	result := db.Table("students").Create(data)
	if result.Error != nil {
		klog.Error("Failed to save student: %s", result.Error.Error())
		resp := &student.Response{
			Code: 500,
			Msg:  "Failed to save student",
		}
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	// 缓存
	lock.Lock()
	cache[data.StudentNo] = data
	lock.Unlock()

	resp := &student.Response{
		Code: 200,
		Msg:  "success",
		Data: strconv.FormatInt(result.RowsAffected, 10),
	}

	c.JSON(consts.StatusOK, resp)
	return
}

// QueryStudent .
// @router /query [GET]
func QueryStudent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.QueryStudentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var resp = &student.Response{}
	// 读缓存
	lock.Lock()
	defer lock.Unlock()
	if value, exist := cache[req.StudentNo]; exist {
		data, err := json.Marshal(value)
		if err != nil {
			klog.Errorf("Failed to query student: %s", err.Error())
			c.JSON(consts.StatusBadRequest, resp)
			return
		}
		resp := &student.Response{
			Code: 200,
			Msg:  "success",
			Data: string(data),
		}
		c.JSON(consts.StatusOK, resp)
		return
	}
	// 缓存中没有
	var stuRes *student.Student
	result := db.Table("students").First(&stuRes, req.StudentNo)
	if result.Error != nil {
		klog.Errorf("Failed to query student: %s", result.Error.Error())
		resp.Code = 200
		resp.Msg = "Failed to query student"
		klog.Errorf("resp: %s", resp)
		c.JSON(consts.StatusNotFound, resp)
		return
	}
	data, err := json.Marshal(stuRes)
	if err != nil {
		klog.Errorf("Failed to query student: %s", err.Error())
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp = &student.Response{
		Code: 200,
		Msg:  "success",
		Data: string(data),
	}
	lock.Lock()
	cache[req.StudentNo] = *stuRes
	lock.Unlock()

	c.JSON(consts.StatusOK, resp)
}
