// Code generated by Kitex v0.9.1. DO NOT EDIT.

package studentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	student "main/kitex_gen/student"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddStudent(ctx context.Context, request *student.SaveStudentReq, callOptions ...callopt.Option) (r *student.Response, err error)
	QueryStudent(ctx context.Context, request *student.QueryStudentReq, callOptions ...callopt.Option) (r *student.Response, err error)
	QueryStudent2(ctx context.Context, request *student.QueryStudentReq, callOptions ...callopt.Option) (r *student.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kStudentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStudentServiceClient struct {
	*kClient
}

func (p *kStudentServiceClient) AddStudent(ctx context.Context, request *student.SaveStudentReq, callOptions ...callopt.Option) (r *student.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddStudent(ctx, request)
}

func (p *kStudentServiceClient) QueryStudent(ctx context.Context, request *student.QueryStudentReq, callOptions ...callopt.Option) (r *student.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryStudent(ctx, request)
}

func (p *kStudentServiceClient) QueryStudent2(ctx context.Context, request *student.QueryStudentReq, callOptions ...callopt.Option) (r *student.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryStudent2(ctx, request)
}
